<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_optionHelper = $this->helper('Codazon\ThemeOptions\Helper\Data');
$_mobileHelper = $this->helper('Codazon\ThemeOptions\Helper\Mobile');
$labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $showHover = $_optionHelper->getConfig('general_section/category_view/hover_product_effect');
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $image_hover = 'category_page_grid_hover';
        $showDescription = $_optionHelper->getConfig('general_section/category_view/show_short_description');
        $showCompareWishlist = $_optionHelper->getConfig('general_section/category_view/show_action');
        $showReviewRating = $_optionHelper->getConfig('general_section/category_view/review_rating_star');
        $pageColumn = $_optionHelper->getPageColumns();                     
            switch($pageColumn){
                case '3columns':                                
                    $columnsDeskClass = 'desktop_'.$_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_3col');
                    $columnsTabClass = 'tablet_'.$_optionHelper->getConfig('general_section/category_view/category_tablet_view/product_row_tablet_3col');
                    break;
                case '1column':                 
                    $columnsDeskClass = 'desktop_'.$_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_1col');
                    $columnsTabClass = 'tablet_'.$_optionHelper->getConfig('general_section/category_view/category_tablet_view/product_row_tablet_1col');
                    break;
                case '2columns':                    
                    $columnsDeskClass = 'desktop_'.$_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_2col');
                    $columnsTabClass = 'tablet_'.$_optionHelper->getConfig('general_section/category_view/category_tablet_view/product_row_tablet_2col');
                    break;
                default:                    
                    $columnsDeskClass = 'desktop_'.$_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_2col');
                    $columnsTabClass = 'tablet_'.$_optionHelper->getConfig('general_section/category_view/category_tablet_view/product_row_tablet_2col');
                    break;  
                }
                //echo $_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_2col');
                //echo $_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_1col');
                //echo $columnsDeskClass;
            $columnsMobileClass = 'mobile_'.$_optionHelper->getConfig('general_section/category_view/category_mobile_view/product_row_mobile');
        if(!$_mobileHelper->isMobile()){    
            $columnsClass = $columnsDeskClass;
        }else if($_mobileHelper->isTablet()){
            $columnsClass = $columnsTabClass;
        }else if($_mobileHelper->isMobile() && !$_mobileHelper->isTablet()){
            $columnsClass = $columnsMobileClass;    
        }
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $image_hover = 'category_page_list_hover';
        $showDescription = $_optionHelper->getConfig('general_section/category_view/show_short_description');;
        $showCompareWishlist = $_optionHelper->getConfig('general_section/category_view/show_action');
        $showReviewRating = $_optionHelper->getConfig('general_section/category_view/review_rating_star');
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $columnsClass = 'desk_1';
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    
    
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="<?php echo $columnsClass ?>" id="category-products-grid">
            <ol class="products list items product-items same-height">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">                   
                        <div class="cdz-hover-section">
                        <div class="cdz-product-top">
                        <?php                       
                        $productImage = $block->getImage($_product, $image);
                        $productHoverImage = $block->getImage($_product, $image_hover);
                        $tmp1 = $productImage->getData('image_url');
                        $tmp1 = explode('/',$tmp1);

                        $tmp2 = $productHoverImage->getData('image_url');
                        $tmp2 = explode('/',$tmp2);

                        if($tmp1[count($tmp1)-1] == $tmp2[count($tmp2)-1]){
                            $productHoverImage = $productImage;
                        }

                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                        }

                        $id = $_product->getId();
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $obj_product = $objectManager->create('Magento\Catalog\Model\Product');
                        $product = $obj_product->load($id);
                        $product_type = $product->getTypeId();
                        $defaultAssociatedProduct = $defaultAssociatedProductId = $templateId = $defaultAssociatedProductTemplateId = "";
                        if ($product_type == "configurable") {
                            $defaultAssociatedProductId = $product->getDefaultAssociatedProduct();
                            $defaultAssociatedProduct = $obj_product->load($defaultAssociatedProductId);
                            if (!empty($defaultAssociatedProductId) && !empty($defaultAssociatedProduct->getPreLoadedTemplate())) {
                                $defaultAssociatedProductTemplateId = base64_encode($defaultAssociatedProduct->getPreLoadedTemplate());
                            }
                        }
                        $productTemplateId = base64_encode($product->getPreLoadedTemplate());
                        $currentStoreId = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getId();
                        $isEnable = $this->helper('Biztech\Productdesigner\Helper\Info')->isEnable($currentStoreId);
                        $isPdEnable = $this->helper('Biztech\Productdesigner\Helper\Info')->isPdEnable($_product->getId());
                        $product = (!empty($defaultAssociatedProductTemplateId)) ? $defaultAssociatedProduct : $product;
                        $templateId = (!empty($defaultAssociatedProductTemplateId)) ? $defaultAssociatedProductTemplateId : $productTemplateId;
                        // check template is enabled or not 
                        if ($templateId) {
                            $design_template = $objectManager->create('Biztech\DesignTemplates\Model\Designtemplates')->load(base64_decode($templateId));
                            $template_status = $design_template['status'];
                        }

                        $media = $objectManager->create('\Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
                        $templateUrl = "";
                        $makeDesignUrl = $this->getUrl('productdesigner', array('_secure' => $this->getRequest()->isSecure())) . 'index/index/id/' . $_product->getId();
                        if ($templateId && $template_status == 1 && $isEnable && $isPdEnable) {
                            $templateUrl = $this->getUrl('productdesigner', array('_secure' => $this->getRequest()->isSecure())) . 'index/index/id/' . $_product->getId() . '/template/' . $templateId;
                            $makeDesignUrl = $templateUrl;
                            /*$templateUrl = "";*/
                            $designImages = $objectManager->create('Biztech\DesignTemplates\Model\Designtemplates')->load(base64_decode($templateId));
                            $imagePath = isset($designImages['image']) ? $designImages['image'] : '';

                            $reader = $objectManager->create('\Magento\Framework\Filesystem')->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)->getAbsolutePath();

                            $file_url = $reader . 'productdesigner/templates/' . $designImages['designtemplates_id'] . '/base/' . $designImages['image'];
                            ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <?php if ($imagePath && file_exists($file_url)): ?>
                                    <img src="<?php
                                    echo $media . 'productdesigner/templates/' . $designImages['designtemplates_id'] . '/base/' . $designImages['image'];
                                    ?>" alt="" />
                                     <?php else: ?>
                                         <?php echo $productImage->toHtml(); ?>
                                     <?php endif; ?>
                            </a>
                        <?php } else {
                            ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <span class="main-image">
                                    <?php echo $productImage->toHtml(); ?>
                                </span>
                                <span class="hover-image">
                                    <?php echo $productHoverImage->toHtml(); ?>
                                </span>
                            </a>
                        <?php } ?>
                        </div>
                        <!--wishlist-->
                        <div class="cdz-product-wishlist show-tooltip">
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showCompareWishlist): ?>
                                <a href="#"
                                   class="action towishlist"
                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                   data-action="add-to-wishlist"
                                   role="button">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                </a>
                            <?php endif; ?> 
                    </div>                                      
                        <?php $labelHelper->showLabel($_product) ?>
                        </div>
                        <?php if($showReviewRating): ?>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?> 
                        <?php endif ?>
                        <div class="product details product-item-details">
                            <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                            
                            
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                            <?php echo $block->getProductDetailsHtml($_product); ?>
                            
                            <div class="product-item-inner">
                                <?php
                                    $addToCartEnable = $this->helper('Biztech\Productdesigner\Helper\Data')->getConfig('productdesigner/general/disable_addtocart_btn_category', $currentStoreId);
                                    $designItEnable = $this->helper('Biztech\Productdesigner\Helper\Data')->getConfig('productdesigner/general/enabled_design_btn_category', $currentStoreId);
                                    $buttonLabel = $this->helper('Biztech\Productdesigner\Helper\Data')->getConfig('productdesigner/dynamic_message/designit_label', $currentStoreId);

                                    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                                    $product->getResource()->getAttribute('media_gallery')
                                            ->getBackend()->afterLoad($product);
                                    $product_images = $product->getAllMediaGalleryImages();
                                ?>
                                <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php
                                            if (isset($isEnable) && $isEnable) {
                                                if (isset($isPdEnable) && $isPdEnable && count($product_images) > 0 && $designItEnable) {
                                                    ?>
                                                    <button type="button" title="<?php echo $buttonLabel ?>" class="action tocart primary list-design-button" onclick="window.location.href = '<?php echo $makeDesignUrl; ?>'"><span><span><?php echo $buttonLabel ?></span></span></button>
                                                    <?php
                                                }
                                            }
                                        ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    </div>
                                </div>
                                <!-- <div class="product actions product-item-actions <?php echo ($isEnable && $isPdEnable) ? 'is-pd-enable' : '' ?>"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        
                                    </div>
                                </div> -->
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                           class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                                 
                            </div>
                            
                            <!--quiclick-addtocart-->
                             <div class="cdz-product-bottom <?php echo $showHover ? 'hover-effect' : 'non-hover' ?>">
                                <div class="cdz-buttons-container">
                                <div class="cdz-buttons-inner">                             
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary show-tooltip">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>                             
                                    <?php echo $this->helper('Codazon\QuickShop\Helper\Data')->getQuickShopButton($_product,'show-tooltip'); ?>
                                    <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <?php if($showCompareWishlist): ?>
                                    <a href="#"
                                       class="action tocompare show-tooltip"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                    </a>
                                    <?php endif ?>
                                </div>
                                </div>
                            </div>                          
                        </div>
                    </div>
                    <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
    <?php if ($block->getMode() == 'grid'): ?>
        <script type="text/javascript">
            require(['jquery','Codazon_ThemeOptions/js/is-mobile'],function($,isMobile){            
                function setClass(){
                    var widthWindow = $(window).width();
                        var list = $('#category-products-grid');
                        if(widthWindow > 1200)
                            list.removeClass().addClass('<?php echo $columnsDeskClass ?>');
                        else if(isMobile.iPad())
                            list.removeClass().addClass('<?php echo $columnsTabClass ?>');
                        else
                            list.removeClass().addClass('<?php echo $columnsMobileClass ?>');
                    }
                    $(window).on('resize',function(){
                        setClass();
                        });
                setClass();                     
            });
        </script>
    <?php endif; ?>
    
<?php endif; ?>
