<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php 
$qtyIncrements = 1;
$dataValidate = $block->getQuantityValidators();
if(isset($dataValidate["validate-item-quantity"]["qtyIncrements"])){
    $qtyIncrements = $dataValidate["validate-item-quantity"]["qtyIncrements"];
}
?>
<?php $buttonTitle = "<span id='fd'>Buy<span style='color: black;font-size: 12px;text-transform: capitalize;font-weight: normal; text-align: center;'>As It Is</span></span>"; ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
            	<div class="qty-minus"> <a class="btn-qty minus" href="#">-</a></div>
		<div class="qty-input">
                	<input type="number"
		               name="qty"
		               id="qty"
		               maxlength="12"
		               value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
		               title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
		               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
		               />
                       </div>
		<div class="qty-plus"> <a class="btn-qty plus" href="#">+</a></div>
            </div>
        </div>
        <script type="text/javascript">
		require(['jquery','domReady!'],function($){
            var dataValidate = $('#qty').data('validate');
            var qtyIncrements = 1;
            if(dataValidate["validate-item-quantity"]["qtyIncrements"] != null){
                qtyIncrements = dataValidate["validate-item-quantity"]["qtyIncrements"]
            }
			$(".btn-qty").click(function (event) {
				var $button = $(this);
				var oldValue = $button.closest('.control').find("input#qty").val();
				var defaultValue = <?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>;
				if ($button.hasClass('plus')) {
					var newVal = parseFloat(oldValue) + qtyIncrements;
				} else {
					if (oldValue > defaultValue) {
					    var newVal = parseFloat(oldValue) - qtyIncrements;
					} else {
					    newVal = defaultValue;
					}
				}
				$button.closest('.control').find("input#qty").val(newVal);
				event.preventDefault();
			});

		});
        </script>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo "BUY As it Is" ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
             <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $currentStoreId = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getId();
                $buttonLabel = $this->helper('Biztech\Productdesigner\Helper\Data')->getConfig('productdesigner/dynamic_message/designit_label', $currentStoreId);
                $isPdEnable = $this->helper('Biztech\Productdesigner\Helper\Info')->isPdEnable($_product->getId());
                $isEnable = $this->helper('Biztech\Productdesigner\Helper\Info')->isEnable($currentStoreId);
                $id = $_product->getId();
                $obj_product = $objectManager->create('Magento\Catalog\Model\Product');
                $product = $obj_product->load($id);

                $product_type = $product->getTypeId();
                $defaultAssociatedProduct = $defaultAssociatedProductId = $templateId = $defaultAssociatedProductTemplateId = "";
                if ($product_type == "configurable") {
                    $defaultAssociatedProductId = $product->getDefaultAssociatedProduct();
                    $defaultAssociatedProduct = $obj_product->load($defaultAssociatedProductId);
                    if (!empty($defaultAssociatedProductId) && !empty($defaultAssociatedProduct->getPreLoadedTemplate())) {
                        $defaultAssociatedProductTemplateId = base64_encode($defaultAssociatedProduct->getPreLoadedTemplate());
                    }
                }
                $productTemplateId = base64_encode($product->getPreLoadedTemplate());
                $product = (!empty($defaultAssociatedProductTemplateId)) ? $defaultAssociatedProduct : $product;
                $templateId = (!empty($defaultAssociatedProductTemplateId)) ? $defaultAssociatedProductTemplateId : $productTemplateId;
                $design_template = $objectManager->create('Biztech\DesignTemplates\Model\Designtemplates')->load(base64_decode($templateId));
                $template_status = $design_template['status'];
                $templateLink = '';
                if(!empty($templateId) && $template_status == 1){
                    $templateLink = 'template/' . $templateId;
                }

                if (isset($isEnable) && $isEnable) {
                    if (isset($isPdEnable) && $isPdEnable) {
                        ?>
                        <div class="product-page-designer">
                            <?php
                            $designerTitle = $buttonLabel;
                            ?>
                            <button type="button"  title="<?php /* @escapeNotVerified */ //echo $designerTitle    ?>" class="action primary tocart product-designer-button" value="<?php /* @escapeNotVerified */ echo $designerTitle ?>"><?php /* @escapeNotVerified */ echo $designerTitle ?></button>
                        </div>
                        <?php
                    }
                }
                ?>  
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('[id="product_addtocart_form"]').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>
<script>
    require([
        'jquery',
    ], function ($) {
        'use strict';
        $('.product-designer-button').click(function () {
            var designerURL = "<?php echo $this->getUrl('productdesigner', array('_secure' => $this->getRequest()->isSecure(), 'id' => $_product->getId())) . $templateLink; ?>";

            var productdata = jQuery("#product_addtocart_form").serializeArray();
            var templateId = "<?php echo $templateId; ?>";
            var templateStatus = "<?php echo $template_status; ?>";
            //create a custom form
            var form = document.createElement("form");
            form.setAttribute('method', "post");
            form.setAttribute('action', designerURL);
            // Create field based on add to cart form field and add in custom form
            var form_data = new FormData();
            jQuery(productdata).each(function (i, data) {
                form_data.append(data.name, data.value);
            });
            var url = "<?php echo $this->getUrl('designtemplates/designtemplates/getTemplateLink'); ?>";
            jQuery.ajax({
                url: url,
                cache: false,
                contentType: false,
                processData: false,
                async: false,
                data: form_data,
                type: 'post',
                dataType: 'json',
                success: function (data)
                {                    
                    if (templateId != "" && templateId != undefined && templateStatus == 1) {
                        var templateUrl = "<?php echo $this->getUrl('productdesigner', array('_secure' => $this->getRequest()->isSecure(), 'id' => $_product->getId())) . 'template/'; ?>" + data.templateId;
                        form.setAttribute('action', templateUrl);
                    }
                    jQuery(productdata).each(function (i, data) {
                        var field = document.createElement("input");
                        field.type = "hidden";
                        field.name = data.name;
                        field.value = data.value;
                        form.appendChild(field);
                    });
                    jQuery("body").append(form);
                    jQuery(form).submit();
                }
            });
        });

    });
</script>
